= GNU Make Gradle Plugin

Provides a wrapper for calling GNU Make from Gradle. This is especially useful
for projects migrating to Gradle or when constructing complex build systems of which
some components utilise GNU make as it build tool. Most common command-line switches
are supported, but for full flexibiliy it is possible to add any additional switch via 
the *switches* property.

== Previous versions of this document

* 0.3 - https://github.com/ysb33r/gnumake-gradle-plugin/blob/GNUMAKE_RELEASE_0_3/README.md
* 0.2 - https://github.com/ysb33r/gnumake-gradle-plugin/blob/GNUMAKE_RELEASE_0_2/README.md
* 0.0.9 - https://github.com/ysb33r/gnumake-gradle-plugin/blob/0.0.9_RELEASE/README.md

== Known compatibility

* 1.0 - Gradle 2.0
* 0.3 - Gradle 2.0
* 0.2 - Gradle 2.0
* 0.1 - Gradle 1.12
* 0.0.9 - Gradle 1.9
* 0.0.3 - Gradle 1.6
* 0.0.2 - Gradle 1.6

==

[source,groovy]
----
buildscript {
  repositories {
	jcenter()
  }
  dependencies {
    classpath 'org.ysb33r.gradle:gnumake:1.0'
  }
}

apply plugin : 'org.ysb33r.gnumake'
----

or if you use Gradle 2.1+

[source,groovy]
----
plugins {
  id "org.ysb33r.gnumake" version "1.0"
}
----

== Supported Attributes

The following attributes are supported:

[cols="4*"]
|===
| Property | Type | Make Switch | Comment
| `alwaysMake` | boolean | `-B` |
| `environmentOverrides` | boolean | `-e` |
| `ignoreErrors` | boolean | `-i` |
| `keepGoing` | boolean | `-k` |
| `jobs` | integer | `-j` |
| `makefile` | string | `-f` |
| `chDir` | string | `-C` |
| `includeDirs` | list | `-I` |
| `targets` | list | | Targets to execute
| `flags` | map | | Variables to pass to make
| `switches` | list | | Arbitrary list of switches to pass to make.
| `executable` | string | | Location of make executable, defaults to 'make'
| `workingDir` | string | | location where to start make from (not the same as *chDir*)
|===

== Deprecated Attributes

| `tasks` | list | | Alias for targets.

== Usage

[source,groovy]
----

buildscript { 
  repositories {
	jcenter()
  }  
  dependencies {
    classpath 'org.ysb33r.gradle:gnumake:1.0'
  }
}

apply plugin : 'org.ysb33r.gnumake'

make {
  targets 'build','install'
  flags  DESTDIR : '/copy/files/here', BUILD_NUMBER : '12345'
}
----

Additional tasks can be created and configured

[source,groovy]
----


import org.ysb33r.gradle.gnumake.GnuMakeBuild

task runMake (type:GnuMakeBuild) {
  targets 'build','install'
  flags  DESTDIR : '/copy/files/here', BUILD_NUMBER : '12345'
}
----

It is also possible to set the executable and makefile name globally for all tasks

[source,groovy]
----
gnumake {
  executable = 'gmake'
  makefile = 'OurOwnMakefileConvention'
  defaultFlags BUILD_NUMBER : '12345'
}
----

Tasks will default to `executable` and `makefile` if not set. `defaultFlags` will be added to the existing flags on
the task unless the `defaultFlags` property on the task is set to `false`.